stages:
  - install
  - test
  - deploy_test
  - deploy_prod

image: kozea/python-node-yarn-postgresql:latest

.artifacts: &artifacts
  artifacts:
    paths:
      - .env/

install:
  stage: install
  script:
    - sed -i '/git+/d' Makefile
    - make install
  <<: *artifacts

test:
  stage: test
  script:
    - make check
  dependencies:
    - install


.image: &image_deploy_jobs
  image: kozea/deploy-tools:latest

deploy_test:
  <<: *image_deploy_jobs
  stage: deploy_test
  script:
    - make deploy-test
  dependencies: []

deploy_prod:
  <<: *image_deploy_jobs
  stage: deploy_prod
  script:
    - make deploy-prod
  dependencies: []
  only:
    - master
